import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import { cn } from "@/lib/utils";
import TRPCProvider from "@/providers/tRPCProvider";
import ClientOnly from "@/providers/ClientOnly";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ThemeToggle from "@/components/ui/themeToggle";
import React from "react";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Graphs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          font.className,
          "antialiased min-h-[calc(100vh-5rem)] dark:bg-background bg-neutral-200"
        )}
      >
        <TRPCProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientOnly>
              {/* Theme Changer rapped by ClientOnly to avoid HYDRATION ERRORS */}
              <ThemeToggle className="fixed top-4 right-4" />
            </ClientOnly>
            {children}
          </ThemeProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
